Repository cartography-cncf/cartography, pull requests merged in 2019-10, with the labels that each got.

#167 Change supported version of neo4j from 3.2 to 3.5.
  .travis.yml
  Makefile
  README.md
  cartography/driftdetect/get_states.py
  tests/data/test_update_detectors/test_detector/2019-01-01 00:00:01.json
  tests/data/test_update_detectors/test_detector/2019-01-01 00:00:02.json
  tests/integration/cartography/data/jobs/test_syntax.py
Labels: WIP, enhancement

#171 Change AWS EC2 intel module to consume query results during ingestion.
  cartography/intel/aws/ec2.py
Labels: bug

#165 Remove usage of old neo4j driver api.
  cartography/driftdetect/get_states.py
  cartography/sync.py
  setup.py
Labels: enhancement

#182 Fix syntax error in Travis file.
  .travis.yml
Labels: bug

#151 Ingest Google Cloud Buckets
  cartography/data/indexes.cypher
  cartography/data/jobs/cleanup/gcp_storage_bucket_cleanup.json
  cartography/intel/gcp/__init__.py
  cartography/intel/gcp/storage.py
  docs/schema/gcp.md
  tests/data/gcp/storage.py
  tests/integration/cartography/intel/gcp/test_storage.py
  tests/unit/cartography/intel/gcp/test_storage.py
Labels: WIP, enhancement

#137 Add Okta intel module.
  README.md
  cartography/cli.py
  cartography/config.py
  cartography/data/indexes.cypher
  cartography/data/jobs/cleanup/okta_import_cleanup.json
  cartography/intel/okta/__init__.py
  cartography/intel/okta/applications.py
  cartography/intel/okta/factors.py
  cartography/intel/okta/groups.py
  cartography/intel/okta/organization.py
  cartography/intel/okta/origins.py
  cartography/intel/okta/roles.py
  cartography/intel/okta/sync_state.py
  cartography/intel/okta/users.py
  cartography/intel/okta/utils.py
  cartography/sync.py
  docs/developer-guide.md
  docs/schema/okta.md
  setup.py
  tests/data/okta/__init__.py
  tests/data/okta/adminroles.py
  tests/data/okta/application.py
  tests/data/okta/groups.py
  tests/data/okta/trustedorigin.py
  tests/data/okta/userfactors.py
  tests/data/okta/users.py
  tests/integration/cartography/data/jobs/test_syntax.py
  tests/unit/cartography/intel/okta/test_admin_roles.py
  tests/unit/cartography/intel/okta/test_application.py
  tests/unit/cartography/intel/okta/test_factor.py
  tests/unit/cartography/intel/okta/test_group.py
  tests/unit/cartography/intel/okta/test_trusted_origin.py
  tests/unit/cartography/intel/okta/test_user.py
Labels: enhancement, keep fresh

#185 Crxcavator: add permission nodes
  cartography/data/indexes.cypher
  cartography/data/jobs/cleanup/crxcavator_import_cleanup.json
  cartography/intel/crxcavator/crxcavator.py
  docs/schema/crxcavator.md
  tests/data/crxcavator/crxcavator.py
  tests/integration/cartography/intel/crxcavator/test_crxcavator.py
Labels: enhancement
