Repository cartography-cncf/cartography, pull requests merged in 2019-09, with the labels that each got.

#158 Add doctoc pre-commit hook to auto-generate tables of contents for all documentation.
  .pre-commit-config.yaml
  README.md
  docs/developer-guide.md
  docs/drift-detect.md
  docs/schema/aws.md
  docs/schema/crxcavator.md
  docs/schema/gcp.md
  docs/schema/gsuite.md
  docs/schema/index.md
  docs/writing-analysis-jobs.md
Labels: enhancement, keep fresh

#157 Add stalebot configuration
  .github/stale.yml
Labels: enhancement

#155 Change AWS sync function names to be consistent throughout the intel module.
  cartography/intel/aws/__init__.py
  cartography/intel/aws/dynamodb.py
  cartography/intel/aws/ec2.py
  cartography/intel/aws/rds.py
  cartography/intel/aws/route53.py
Labels: enhancement, keep fresh

#147 Fix incorrect linking of AWS users to groups.
  cartography/intel/aws/iam.py
Labels: bug, keep fresh, needs-tests

#163 Fix incorrect ’lastupdated’ for vpc peering.
  cartography/intel/aws/ec2.py
Labels: bug, needs-tests

#162 Add initial documentation on creating custom sync scripts.
  docs/developer-guide.md
Labels: documentation
