Repository cartography-cncf/cartography, pull requests merged in 2019-11, with the labels that each got.

#130 Adding ELBv2 Support
  README.md
  cartography/data/indexes.cypher
  cartography/data/jobs/analysis/aws_ec2_asset_exposure.json
  cartography/data/jobs/cleanup/aws_ingest_load_balancers_v2_cleanup.json
  cartography/intel/aws/ec2.py
  docs/schema/aws.md
  tests/data/aws/ec2.py
  tests/integration/cartography/intel/aws/test_ec2.py
Labels: enhancement, keep fresh

#204 Skip Okta sync if API key is undefined
  cartography/intel/okta/__init__.py
Labels: WIP

#189 Fix query for gcp firewall ingress deny rules.
  cartography/intel/gcp/compute.py
Labels: bug, keep fresh

#181 Replace custom templating with python Template in AWS EC2.
  cartography/intel/aws/ec2.py
Labels: improvement
